### ISSUE TITLE
[Feature Request] Add Support for Choosing Branches

### ISSUE THREAD

**Issue by cgrymala** [mAAdhaTTah/wordpress-github-sync#110]
I love this plugin and am happily using it. However, one thing that would make it infinitely more useful is if there was some way to choose specific branches of a repo when syncing.

If we were able to switch/choose branches, we could potentially use this plugin to sync/manage content between a staging site and a production site. We could use one branch for staging and a separate branch for production, then, if someone does a bulk of their work on the staging site, we could simply pull/merge the staging branch into the production/master branch and have all of their content pushed automatically to the production site (allowing us to more easily deal with conflicts than we do when trying to export/import content through traditional WP methods).

At the moment, obviously, we can do this sort of thing by setting up a production repo, then forking it to a separate repo for staging; but it seems like it might be easier to manage if we could simply choose branches within the same repo. Thanks in advance for considering this request, and I totally understand if it's outside of the scope for this plugin.

**Comment by mAAdhaTTah** [comment]
This actually might not be that difficult, though I'll probably customize it via WordPress filter rather than an option in the settings page. The only thing I'll throw out there in advance when doing something like this is making sure you start with a matching database in both environments, so that the post IDs match. Otherwise, things can get messy, quickly.

[Someone else had asked about using WPGHS to sync multiple sites](https://wordpress.org/support/topic/localhost-12), so I can make it customizable enough that you can do it yourself, but just know in advance my ability to support that particular usecase is going to be limited.

**Comment by cgrymala** [comment]
Understood. Thank you very much.

**Comment by mAAdhaTTah** [comment]
@cgrymala See #111. There are actually 2 filters you'll need to configure. I haven't written the documentation, but it will live [here](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki/Keep-Multiple-Sites-in-Sync-with-WordPress-GitHub-Sync).
