### ISSUE TITLE
Improve Documentation for Non-Developers

### ISSUE THREAD

**Issue by yawnbox** [mAAdhaTTah/wordpress-github-sync#120]
The language used, especially in the "Configuring the Plugin" section requires that people are intimately familiar with GitHub. For instance:

"Make sure the repository has an initial commit or the export will fail"

What? Why doesn't "Export to GitHub" do that for me? I'm still getting this error: "Export to GitHub failed with error: Method GET to endpoint".

Others:

"GitHub hostname"

What is that? Do I change it from the default? Where do I find it? You need to be explicit.

"Webhook Secret"

I Googled that to see that it, in fact, needs to be high-entropy. But you don't explain that in the plugin interface or directions.

Overall, it does not appear that you asked for input from outsiders before writing this. Please lower the bar so non-technical people can adopt it. I have a GitHub account because I provide projects with feedback. This is the first time I'll actually be using version control for myself (if I can get this to work).

Cheers

**Comment by malsony** [comment]
Git (or GitHub) is a total different "system" for text or other files and it has some strict requirements of a repository, for example, a commit every time for any change(s) of the file(s) in the repository. I am afraid that WPGHS is unable to make the initial commit for you, so it is suggested to be done on GitHub side.

1. "GitHub hostname". If your repo is public, you don't have to change the default entry;
2. "Webhook Secret". I believe that there is a link in the setting page of WPGHS, just click it and follow the instructions in README.md of WPGHS;

This is a non-commercial project, and I also find it hard to "fully-customized" on my own. Hope the setting interface can be more interactive because I am non-technical and new to GitHub and WPGHS; I made it working and I believe you can make it, too.

**Comment by mAAdhaTTah** [comment]
Thanks for the feedback. I'll definitely a look and see what I can do about updating some of the documentation, as well as link out to additional documentation where appropriate. A lot of the documentation was just written once and that's it. It's pretty much just me at this point, so I rely on this kind of feedback to know where the issues are.

Do you feel the same way about the README? I wanted to make that clear and provide enough instruction for non-developers.

**Comment by mAAdhaTTah** [comment]
Related: Implementing #2 would mitigate a lot of this problem.

**Comment by mAAdhaTTah** [comment]
I tried to improve the labels and cleanup the documentation to push people towards the wiki. The basic setup (with the oAuth token) should be as easy as possible for non-developers, but most of the other customization is going to done through filters, which does require some basic knowledge of how WordPress hooks function and how to customize them. That's always going to be somewhat of a learning curve for people.
