### ISSUE TITLE
Adding taxonomy/category to file header?

### ISSUE THREAD

**Issue by BoweFrankema** [mAAdhaTTah/wordpress-github-sync#122]
I was wondering if it would be possible to add categories/taxonomies to the file header so that when you are creating a post via GitHub you can assign a category/taxonomy to the post/CPT?

**Comment by mAAdhaTTah** [comment]
Yes, see these filters: [`wpghs_post_meta`](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki/Customizing-WordPress-GitHub-Sync-with-Filters#wpghs_post_meta) for adding the data on the export process and [`wpghs_pre_import_meta`](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki/Customizing-WordPress-GitHub-Sync-with-Filters#wpghs_pre_import_meta) for grabbing it on the import process.

The first filter should be pretty straightforward: You get an array with the key/value pairs for the frontmatter, and you add whatever values you'd like and return the array.

For the second filter, you'll get the array with all the data. Grab the value for the key you set in the first step, save it manually where it needs to go, and return the array *with the key removed.* This array gets saved into `post_meta`.

That should be enough to get you going. I'm going to close this ticket, but feel free to respond if you need additional support.

If you came here from the [wiki](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki/Advanced-Configurations), feel free to post your questions here as well.

**Comment by ytjohn** [comment]
I was wondering if you could give an example? For me, I'm trying to set the post_date on a post, like in #148.  I had copied all my static markdown posts from an existing site, then edited the frontmatter to match.

Ie, I'll commit a bunch of files like so in my repo:

```
---
post_title: An older post
post_date: 2014-11-09 10:06:24
---
This is a test post
```

I also tried `date: 2014-11-09 10:06:24` instead of `post_date: 2014-11-09 10:06:24`.

wordpress-github-sync will pull these files in, but disregard the post_date and set the post date to match the time of the commit and then all of my posts will show up as if I had just posted them today. 

Is `wpghs_pre_import_meta` something I have to edit in the the plugin's code, or is this something I can put in frontmatter?

**Comment by litefeel** [comment]
@BoweFrankema  
For tags and categories, you can use the plugin `wp-github-sync-meta`

https://github.com/litefeel/wp-github-sync-meta

~~~
---
...
tags:
  - my tag
categories:
  - my category
---
~~~

**Comment by sivyel** [comment]
how to add featured image ?
