### ISSUE TITLE
If markdown file name changed post no longer recognized by WordPress

### ISSUE THREAD

**Issue by DavidWells** [mAAdhaTTah/wordpress-github-sync#129]
If I have a file in my /_posts directory locally and I change the name of that file, WordPress no longer recognizes it on the sync and deletes the post.

Would it be possible to use the ID in the markdown frontmatter to be the reference point? ( Not sure how the plugin is currently updating posts. shas? )

Then no matter what you rename files to, the correct WordPress post ID will be updated when you push to Github.

```
// If ID in frontmatter, use ID to update corresponding post in WP

---
ID: 64
post_title: Lets add new post
author: David Wells
post_date: 2016-01-24 02:41:47
post_excerpt: ""
layout: post
permalink: http://xxxxxxxxxxxxxx.com/?p=64
published: true

---
```

**Comment by mAAdhaTTah** [comment]
Can you provide the webhook data from GitHub when this happens? I have an idea what might be causing this, but I'm not sure how GitHub transmits git renames. If it's as an add and delete, then the issue is [here](https://github.com/mAAdhaTTah/wordpress-github-sync/blob/master/lib/import.php#L50-L64), which is where we remove any files that GitHub tells us have been deleted.

The only thing is you really _shouldn't_ change the filename in your git repo. Those filenames are set by WordPress on export. If you want to customize the filename, the filter is [here](https://github.com/mAAdhaTTah/wordpress-github-sync/blob/master/lib/post.php#L213), but I don't think you should edit that in git directly.

**Comment by mAAdhaTTah** [comment]
Without feedback, I can't fix this issue, and filenames shouldn't really be edited in `git` here. Going to close. Feel free to open with more information.
