### ISSUE TITLE
Support for syncing wp-uploads

### ISSUE THREAD

**Issue by benbalter** [mAAdhaTTah/wordpress-github-sync#13]

**Comment by mAAdhaTTah** [comment]
I think the only way this would be possible is if there was an API for [Git LFS](https://git-lfs.github.com/).

**Comment by kennyfraser** [comment]
I have this partially working, ( git -> wp, but not git <- wp yet ) but am running in to memory limit issues. I added mine type detection to blobs, if the mine type is an image I save the blog contents to disk and side load into the media library.

In a repo with 125 pages and 6 ~100k images I am hitting my 500M php memory limit though. Disabling the in memory cache seems to help, but still working through that issue.

**Comment by mAAdhaTTah** [comment]
Yeah, I suspect there are going to be a _lot_ of issues related to memory and the like, trying to commit and push all your images, which is why I'm not entirely convinced this is even something we should include in the project. I'd be happy to make sure the required hooks are exposed to make this something you could write into a separate plugin, but I don't know as I have the motivation to deal with the headaches that are going to come with trying to support this feature.

**Comment by kennyfraser** [comment]
I agree. Removing the in memory cache seems to have solved the issue for now, but we will be working with images in the repo on a trial basis, potentially removing them later if there are to many issues. 

Originally I was trying to develop a separate plugin, but have since ended up heavily modifying this one as well.

I added the concept of "blob processors". Blob processing functions are assigned to blobs based on the blob's mine type and file extension, it is working well so far.

**Comment by lite3** [comment]
i want export wp-uploads to github. because github is my backup.

**Comment by mAAdhaTTah** [comment]
If I'm being perfectly honest, I'm not going to implement this feature in WPGHS core. I'm happy to make hooks available, if a plugin would like to extend WPGHS to make this possible, but there's no chance I would use it (since I don't really think it's a good idea), and it sounds like an incredible amount of work to maintain. If anyone on this thread wants to tackle it, feel free to open any issues/PRs in order to expose the hooks you need, but I'm going to close this issue since this isn't a feature the main project will implement.

**Comment by eduardogoncalves** [comment]
Hi, what type of encoding do I have to use in files/images to send them to github? Where can I find about size limit?

I tried to encode image to base64, but at github side only get the string value...
![image](https://user-images.githubusercontent.com/4308648/31015858-26799786-a4f0-11e7-8c93-83a64f9d96f1.png)

And if I set `$data->encoding = "base64";` in `to_blob()` function, it breaks:
![image](https://user-images.githubusercontent.com/4308648/31015907-72ea0470-a4f0-11e7-8402-a6d0b2f59c68.png)
