### ISSUE TITLE
Possible Cloudflare (CDN) Interference - Invalid Payload

### ISSUE THREAD

**Issue by shaneholloman** [mAAdhaTTah/wordpress-github-sync#137]
I have set a test repo here https://github.com/shaneholloman/3dwurld  
The WordPress location is here https://3dwurld.com
My server profile is here: http://builtwith.com/?https%3a%2f%2f3dwurld.com

I seem to be getting a good 200 response but with invalid payloads when a change is made on the repo  Additionally Import and Export from the plugin states successful, but nothing will sync to or from WordPress and Github  

I have attached some screenshots in hope this will validate/de-validate my settings. So if all is setup correctly on both ends maybe it's cloudflare interfering?  

![token](https://cloud.githubusercontent.com/assets/1563909/14873794/251f8606-0d4e-11e6-95a7-15e7c87559e6.png)
![webhook](https://cloud.githubusercontent.com/assets/1563909/14873797/252591ea-0d4e-11e6-9884-709c9a9799ac.png)
![wordpress](https://cloud.githubusercontent.com/assets/1563909/14873795/2520abee-0d4e-11e6-8ec5-fb92b0f1c848.png)
![invalid-payload](https://cloud.githubusercontent.com/assets/1563909/14873796/2522cbd6-0d4e-11e6-8e66-f484db79c51c.png)

Thank you in advance

**Comment by mAAdhaTTah** [comment]
Yeah, we've gotten this issue before ([see here](https://github.com/mAAdhaTTah/wordpress-github-sync/issues/69)). I'm not really sure there's anything we can do about this, since the payload requires the secret to validate and if Cloudflare is modifying the headers, the secret won't validate.

**Comment by shaneholloman** [comment]
I have given cloudflare a detailed support request regarding a solution for this... I suspect it will include a pagerule

**Comment by shaneholloman** [comment]
@mAAdhaTTah here's what Cloudflare has asked 

> Hi there,
>
>Thanks for contacting CloudFlare support. We do add several headers and some headers are changed due to the way origin requests are done (e.g. encoding, keep-alive headers, etc). So there's no guarantee that the request will come through CloudFlare exactly as it was sent. Which header specifically is causing issues for you?
>
>Best Regards,
>
>Justin
>CloudFlare | Support Engineer  

I'm not sure what to relay to Justin on this, maybe this would be easy for you to answer?

**Comment by mAAdhaTTah** [comment]
Actually, I may have spoke too soon. If we were seeing CloudFlare interfering with the headers, the error message code would be `invalid_headers` rather than `invalid_payload`, which is shown in the last screenshot you provided. So it might not be their fault.

Some questions to help me pinpoint the issue:

1. Are you hooking into and modifying any of the WPGHS hooks or is this just a standard install?
2. Are you importing/exporting solely to the master branch, or were you testing on another branch? I don't see the commits in that repo that I might expect from someone testing the plugin, unless you've deleted them.
3. Were you expecting the README.md to get imported? We explicitly ignore the README since we don't expect people to want a README on their site. Additionally, the posts/pages are imported/exported into subfolders based on their post type.
4. You tested a full site export by clicking the "Export to GitHub" link and got no response? When you refresh the settings page after click the export to GitHub, you should see a success or error message. If you don't, then the code is erroring out somewhere, which means the next step would be to enable `WP_DEBUG` and `WP_DEBUG_LOG`:

    ```php
    define('WP_DEBUG', true);
    define('WP_DEBUG_DISPLAY', false);
    define('WP_DEBUG_LOG', true);
    ```

    And see what the logs tell us.

I should be able to narrow down what part of the code is causing the issue with that.

**Comment by mAAdhaTTah** [comment]
I'm going to close this, because I don't think we can handle all possible CDN configurations. If more information is provided, I'd be happy to reopen and investigate this issue.
