### ISSUE TITLE
Feature Request: Would be great if this plugin supported git only (without hub)

### ISSUE THREAD

**Issue by COLABORATI** [mAAdhaTTah/wordpress-github-sync#145]
The same features with my own git repo at home would be great! Thanks!

**Comment by mAAdhaTTah** [comment]
Unfortunately, there's really no way this is going to happen. The complexity involved in building out the functionality to talk to the GitHub API was substantial, and so the complexity in expanding out that functionality to talk to other git-like APIs (like Bitbucket or Gitlab) would be substantial as well. In addition to needing to interact with git directly, which itself is more complex that dealing with an HTTP request, it would require the plugin user to have git installed on their system, something you can't really rely on in a world of shared and managed hosts.

Lastly, because it's not something I plan on using, it's not something I'm going to be able to dedicate a lot of time to building. I may have mentioned this before, in response to the suggestion to support Bitbucket, but I'm very open to ensuring the proper hooks and filters are available to allow someone to build an extension that talks to other git-like APIs or even git directly. If this becomes something you try to build, I'm happy to provide additional exposure points, if they're necessary to make it work.

But unfortunately, I'm not going to build this.

Thanks for the suggestion. Feel free to use this ticket to continue the discussion, but otherwise, closing as `wontfix`.
