### ISSUE TITLE
RFC: Remove Handling of Custom Post Meta

### ISSUE THREAD

**Issue by jihunx** [mAAdhaTTah/wordpress-github-sync#159]
Hi.

I'm using the 'Featured Image From URL' plugin now(to use external featured image).

1. Exporting a page from Wordpress to GitHub
2. Import same page from GitHub to Wordpress(then I didn't  make any change to that page.)
3. And then, the page registerd featured image or not, a dummy featured image added to the page always as below(image name is 'Array').

![image](https://cloud.githubusercontent.com/assets/25073589/22495788/65cc4300-e887-11e6-95e4-8c84c3e44dc6.png)

![image](https://cloud.githubusercontent.com/assets/25073589/22495811/884d5c7a-e887-11e6-948e-ed3ce0cdbd12.png)

actual registered featured image doesn't work.
![image](https://cloud.githubusercontent.com/assets/25073589/22495821/ac414be6-e887-11e6-9181-643d75ee4959.png)

So my blog layout is broken because of this.
How can I fix this?

But post works well.

![image](https://cloud.githubusercontent.com/assets/25073589/22495852/d8d0c18c-e887-11e6-8923-879102393de3.png)

![image](https://cloud.githubusercontent.com/assets/25073589/22495864/feb40972-e887-11e6-840f-b762a1b355ef.png)

**Comment by mAAdhaTTah** [comment]
What's the plugin you're using for the featured image?

**Comment by jihunx** [comment]
this. https://wordpress.org/plugins/featured-image-from-url/
Posts also have problem too. 
When I repeat export and import, array function is entered in featured image url(fifu_image_url).

**Comment by mAAdhaTTah** [comment]
I'll have to dig into their code to figure why. In the meantime, you can remove it with `wpghs_pre_import_meta`, and `unset` the `fifu_image_url` from the meta array before it gets saved to the db.

**Comment by mAAdhaTTah** [comment]
Hmmm, I may have to update how we're currently handling custom meta data. The `get_post_custom` we're using to get all of the posts' meta data returns an array. Because WordPress allows you to use the same key with multiple values, the key (in this case `fifu_image_url`) is associated with an array of strings, rather than the single string we want.

On import, we take that array and stuff it back into the `post_meta` and that's how we end up with the problem you see here. It's clear to me that there's a mismatch between the import & export that causes there sort of breakage, but given WordPress's odd behavior in handling meta, I don't actually think there's a way we can solve this in a robust way.

I kind want to drop having WPGHS handle custom meta at all. We already have the hooks required to allow any user to customize what meta is imported/exported and how that data is structured. That said, I'm not entirely sure how that will affect users.

I've renamed the issue to better reflect the problem and **would like users of the plugin to weigh in** on how they're currently using this for custom post meta and whether removing the handling of that custom meta from the plugin would be detrimental.

**Comment by jihunx** [comment]
Thanks for your kind answer.
Could you give me more detail explain how to remove `wpghs_pre_import_meta' and unset the `fifu_image_url` from the meta array?
I want to delete all existing sync data and start totally new sync from now on.
If so, am I supposed to delete this row `$meta = apply_filters( 'wpghs_pre_import_meta', $post->get_meta(), $post );` from the `database.php`? 
I'm not a developer, so could you explain it step by step for me?

**Comment by mAAdhaTTah** [comment]
In `wp-content`, create or open the mu-plugins folder and create a plugin file there called `wpghs-custom-filters.php`. In it, paste the below code:

```php
add_filter('wpghs_pre_import_meta', function ($meta) {
  unset($meta['fifu_image_url']);
  return $meta;
});
```

**Comment by jihunx** [comment]
Thanks a lot.
Until now, there was no problem.

**Comment by mAAdhaTTah** [comment]
@litefeel Would this have any impact on your usage of WPGHS? I see you created a plugin to handle this.

**Comment by drallgood** [comment]
@mAAdhaTTah 
I use both `wpghs_post_meta`and `wpghs_pre_import_meta` to basically export/import podcast episodes (tying together the  podlove plugin and this one).
Not sure how this would be impacted by your proposed change, but I can share my code if you need it.
