### ISSUE TITLE
Replace exporting file title to another one

### ISSUE THREAD

**Issue by jihunx** [mAAdhaTTah/wordpress-github-sync#160]
Hello.

It's me, again.
Sorry to bother you.

In Korean(my native language), exported file title is too long to deal with file operations.
For example,
* original title :  `엑셀 여러 열의 값이 동시에 중복될 때 조건부 서식 지정하는 방법`
* exported title : `2016-11-18-%ec%97%91%ec%85%80-%ec%97%ac%eb%9f%ac-%ec%97%b4%ec%9d%98-%ea%b0%92%ec%9d%b4-%eb%8f%99%ec%8b%9c%ec%97%90-%ec%a4%91%eb%b3%b5%eb%90%a0-%eb%95%8c-%ec%a1%b0%ea%b1%b4%eb%b6%80-%ec%84%9c%ec%8b%9d-%ec%a7%80`

I can't upload these file to cloud server or copy another folder sometimes.
Can I replace exporting file title to another one like permanent link number(e.g. http://bimmermac.com/**766**) or original character, or anything short one?(my hope is original character.)

And if I want to do so, how do I have to do?

![image](https://cloud.githubusercontent.com/assets/25073589/22590845/a02e0500-ea54-11e6-8c4b-34e1327a2cd1.png)

**Comment by mAAdhaTTah** [comment]
Oh wow... huh. I'll have to think about this one. I feel like we _should_ be able to export the filenames w/ the Korean characters as-is, but it looks like they're getting converted to... URL encoding? Maybe? Maybe that's the post slug...

Yeah, sorry, I'll need to take a closer look at this.

**Comment by jihunx** [comment]
Yes, you right. It converted to URL encoding by character references.
I am waiting for your genius solution.
Thank you.

**Comment by mAAdhaTTah** [comment]
Can you provide an example of one of these posts on your site? Wondering how WordPress handles the URL.

**Comment by jihunx** [comment]
Here it is.
URL : http://bimmermac.com/766
Original title : 엑셀 여러 열의 값이 동시에 중복될 때 조건부 서식 지정하는 방법
Encoded title : 2016-11-18-%ec%97%91%ec%85%80-%ec%97%ac%eb%9f%ac-%ec%97%b4%ec%9d%98-%ea%b0%92%ec%9d%b4-%eb%8f%99%ec%8b%9c%ec%97%90-%ec%a4%91%eb%b3%b5%eb%90%a0-%eb%95%8c-%ec%a1%b0%ea%b1%b4%eb%b6%80-%ec%84%9c%ec%8b%9d-%ec%a7%80

And I attach exported file here.

**Comment by dirkhh** [comment]
You could write a small plugin that adds a filter to create different filenames

```
function my_names($post_name, $post_object) {
    return $post_object->id
}
add_filter ( 'wpghs_filename', 'my_names', 10, 2 );
```

Entirely untested, but that should be enough to have it export the different files with their IDs instead of the encoded post title.

**Comment by jihunx** [comment]
OK, Thank you.

I'll test it in my local stage wordpress first.

**Comment by devmidai** [comment]
same problem... I want to use the english name as url but it always change to a long string.

**Comment by mAAdhaTTah** [comment]
@jihunx When you generate the permalinks, are you doing that by modifying the post slug via the post editor screen or are you generating the permalinks `%post_id%`? If you're using `%post_id%`, the reason you're getting this is because the `post_name` doesn't change, as it's generated when the post is created, but ignored for the permalinks.

But we're using the `post_name` in order to generate the filename for GitHub. You have two options for this:

Use the code @dirkhh suggested above, with a minor modification:

```php
function my_names($post_name, $post_object) {
    return $post_object->id . '.md';
}
add_filter ( 'wpghs_filename', 'my_names', 10, 2 );
```

Make sure it has the `.md` extension.

The other is modify the `post_name`, which you can do on the editor screen by clicking "Screen Options" -> Check "Slug" -> scroll down and edit. This also gives you a bit more custom control over the filename, while the filter applies a blanket rule across all filenames.

As for the original, looking through the docs, I _think_ I should use `sanitize_file_name` here, rather than `sanitize_title`, since that would give me a more appropriate value.
