### ISSUE TITLE
Work with private repos?

### ISSUE THREAD

**Issue by 949mac** [mAAdhaTTah/wordpress-github-sync#169]
How can we make this happen? I'm concerned google will nail me for duplicate content if it's public.

**Comment by mAAdhaTTah** [comment]
It should work fine with private repos, as long as the API token had access to the repository. If you're using GitHub Enterprise, you may need to configure the API root, but otherwise, there should be no issue. 

I'm going to close this issue, but feel free to ask questions or reopen if you run into issues.
